
route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'email-me'
receivers:
- name: 'email-me'
  email_configs:
  - to: aadilshakri@gmail.com
    from: gonthestoneageboy@gmail.com
    smarthost: smtp.gmail.com:587
    auth_username: "gonthestoneageboy@gmail.com"
    auth_identity: "gonthestoneageboy@gmail.com"
    auth_password: "nobitanobi1212"
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
